name: build and test

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
      - '**.fs'
      - '**.fsproj'
      - '**/*.fsx'
      - '.github/workflows/dotnet.yml'
      - 'README.md'

jobs:
  build-and-test:
    name: build-and-test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore StringCalculator/StringCalculator.Lib/StringCalculator.Lib.fsproj

    - name: Build
      run: dotnet build --configuration Release --no-restore StringCalculator/StringCalculator.Lib/StringCalculator.Lib.fsproj

    - name: Test
      run: dotnet test --no-restore --verbosity normal StringCalculator/StringCalculator.Lib/StringCalculator.Lib.fsproj
